---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-7.2
  - name: centos-6.8
  - name: centos-5.11
    attributes:
      hashicorp-vault:
        config:
          disable_mlock: true

suites:
  - name: default
    provisioner:
      policyfile: test/fixtures/policies/default.rb
